# Generated by Django 3.0.3 on 2021-01-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210109_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SuperMarket', 'SuperMarket'), ('Fashion', 'Fashion'), ('Electronics', 'Electronics'), ('Beauty', 'Beauty')], max_length=200, null=True),
        ),
    ]
